language: csharp

sudo: required
dist: trusty

env:
  global:
    secure: "WJMNlWAxmV60t9BdgbJE06EG+8d5CYI33/q4ONL5khXw/gHQ+F8USEFjRF+RigS+HbrEROWDM74HldX47gnaXq94w3mUT8JChoIyCpyBXrtSsZgseT6VDSS+vREV8btKY5wa3Tmb+bLPFVEkH86EKbVuSXENav+DLn9bS9ktzdDIzgVya90zPDV3fZeShxtxUMGPLgGOitehpWAExVvY3kO49nTzasiqXv3a6oW60jJIAtgV0D22ZXy1yoc3CskWthso20GeSmlKeS3GobjegDFxNJvYjT9npt8a53sj9+llFP//bChaMvM4/A3UJQyl0cViCgmwQV1Nq38/QBPf2Oc4C/gDyi1DAyXwfhbBIykeHy9jpfYqEptPXTH3mkpz8OJaBbu+tTgiCCkl0XoYTl773s7IEom35gLoDizgsGzqcGVREJ5tCdiFcV0cFhuIJ+J5IKP2wKAx6zWRYN5Oypad5563efF6tVOvsOHEABA8nQdjE3KhQ+xgvW1pemP6iL/wIAkfnRzRsrCivAU5hvJ5p6u3C9zFhn2cGzKVAggCir57Og5JX5zS5CnXF+wbrccLuUrL3LLByMaXqbEC36qWIzaxcVaQX+Ga2UiySQ/ZJYzPv18T6k91o1mZG9ggDAbpmSjOzsUPJbp9Bko7jwh8+Uj0FZjy/Z9og/hEqkA="

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update -qq
  - sudo apt-get install -qq dotnet-dev-1.0.0-preview2-003121

install:
  - pushd YaasServicePatterns && dotnet restore && popd

script:
  - pushd YaasServicePatterns && dotnet pack -c Release && popd

after_success:
  "nuget push YaasServicePatterns/bin/Release/YaasServicePatterns.0.0.1-beta.nupkg $NUGET_API_KEY -Source https://www.nuget.org/api/v2/package"